import type { AnalysisResult } from "./types";

/** A short verdict label derived from the numeric score. */
export function scoreVerdict(score: number): string {
  if (score >= 75) return "Strong match";
  if (score >= 50) return "Partial match";
  return "Weak match";
}

/** Render a bullet list, or a placeholder line when the list is empty. */
function bulletList(items: string[], empty: string): string {
  if (items.length === 0) return `_${empty}_`;
  return items.map((item) => `- ${item}`).join("\n");
}

/**
 * Turn an analysis result into a self-contained Markdown report the user can
 * download, share, or paste into notes. Pure — no DOM or browser APIs.
 */
export function buildReport(result: AnalysisResult): string {
  const { score, summary, matchedSkills, missingSkills, suggestions } = result;

  const sections = [
    "# Resume match report",
    "",
    `**Match score:** ${score}/100 — ${scoreVerdict(score)}`,
    "",
    summary.trim() || "_No summary provided._",
    "",
    `## Matched skills (${matchedSkills.length})`,
    bulletList(matchedSkills, "No overlapping skills detected."),
    "",
    `## Missing skills (${missingSkills.length})`,
    bulletList(missingSkills, "Nothing major missing."),
    "",
    "## Tailored bullet suggestions",
    bulletList(suggestions, "No suggestions provided."),
    "",
    "---",
    "_Generated by Resume Matcher._",
  ];

  return sections.join("\n") + "\n";
}

/** A filesystem-safe filename for the downloaded report. */
export function reportFilename(score: number): string {
  return `resume-match-report-${score}.md`;
}
