import type { AnalysisResult } from "./types";

/** A short verdict label derived from the numeric score. */
export function scoreVerdict(score: number): string {
  if (score >= 75) return "Strong match";
  if (score >= 50) return "Partial match";
  return "Weak match";
}

/** Render a bullet list, or a placeholder line when the list is empty. */
function bulletList(items: string[], empty: string): string {
  if (items.length === 0) return `_${empty}_`;
  return items.map((item) => `- ${item}`).join("\n");
}

/**
 * Turn an analysis result into a self-contained Markdown report the user can
 * download, share, or paste into notes. Pure — no DOM or browser APIs.
 */
export function buildReport(result: AnalysisResult): string {
  const { score, summary, categories, matchedSkills, missingSkills, suggestions } = result;

  const sections = [
    "# Resume match report",
    "",
    `**Match score:** ${score}/100 — ${scoreVerdict(score)}`,
    "",
    summary.trim() || "_No summary provided._",
    "",
  ];

  if (categories.length > 0) {
    sections.push(
      "## Score breakdown",
      ...categories.map((c) => `- ${c.name}: ${c.score}/100`),
      "",
    );
  }

  sections.push(
    `## Matched skills (${matchedSkills.length})`,
    bulletList(matchedSkills, "No overlapping skills detected."),
    "",
    `## Missing skills (${missingSkills.length})`,
    bulletList(missingSkills, "Nothing major missing."),
    "",
    "## Tailored bullet suggestions",
    bulletList(suggestions, "No suggestions provided."),
    "",
    "---",
    "_Generated by Resume Matcher._",
  );

  return sections.join("\n") + "\n";
}

/** A filesystem-safe filename for the downloaded report. */
export function reportFilename(score: number): string {
  return `resume-match-report-${score}.md`;
}

/**
 * Join the tailored bullet suggestions into a plain-text block ready for the
 * clipboard — one dash-prefixed bullet per line, blanks dropped. Pure.
 */
export function suggestionsToText(suggestions: string[]): string {
  return suggestions
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map((s) => `- ${s}`)
    .join("\n");
}
